services:
  pygeo-server:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile        
    ports:
      - "8000:8000" 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app  # Ensure Python finds the app module
      - PYTHONWARNINGS=ignore
    volumes:
      - ./app:/app/app  # Bind mount to ensure app code is copied
      - ./data:/app/data  # Bind mount to ensure data is copied    

  # benchmark:
  #   extends:
  #     service: pygeo-server
  #   volumes:
  #     - ./.github/data:/data

  # nginx-pygeo-server:
  #   extends:
  #     service: pygeo-server
  #   ports: 
  #     - 8081:8081      
  #   environment:
  #     - PORT=8081
  #     - PYGEO_SERVER_API_ROOT_PATH=/api/v1/pygeo-server
  #   depends_on:
  #     - pygeo-server  

  nginx:
    image: nginx:latest        
    ports:
      - 80:80
    volumes:
      - ./dockerfiles/nginx.conf:/etc/nginx/nginx.conf  # Bind mount to ensure nginx configuration is copied
    depends_on:
      - pygeo-server
    command: [nginx-debug, '-g', 'daemon off;']
